#!/usr/local/bin/python3

# if and else are conditionals
a, b = 5, 1

if a < b:
    print('a ({}) is less than b({})'.format(a, b))
else:
    print('a ({}) is not less than b ({})'.format(a, b))

# condtional expression in Python
print("foo" if a < b else "bar")
